name: maxi_thread
description: Base threading system for Dart and Flutter that enables background task execution, easing concurrency management and improving application performance. It abstracts background execution for systems that support concurrency and those that cannot (e.g. web)
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  meta: ^1.17.0
  path: ^1.9.1
  rxdart: ^0.28.0

  maxi_framework:
  #git:
    #  url: https://github.com/MaxiCamilo/maxi_framework.git
    #  ref: main
    path: ../maxi_framework

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
